/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mde.es;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
    Alimentacion alimentoAlimentac = new Alimentacion("asdasd","23434234",true);
    System.out.println(alimentoAlimentac);
    
    }
}
